# require_relative 'basic/basic_puts'
# require_relative 'basic/basic_variable'
# require_relative 'basic/user_input'
# require_relative 'basic/basic_strings'
# require_relative 'basic/basic_quiz'
# require_relative 'control_structure/if_sentence'
# require_relative 'control_structure/case_sentence'
# require_relative 'control_structure/for_sentence'
# require_relative 'control_structure/while_sentence'
# require_relative 'control_structure/ternary_operation'
# require_relative 'control_structure/logical_operation'
require_relative 'control_structure/boolean_value'